[project]
name = "echo-server"
version = "0.1.0"
description = "echo-server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["fastapi", "uvicorn"]

[project.scripts]
echo_server = "echo_server:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest-asyncio>=0.25.0",
    "pytest>=8.3.4",
]
