[project]
name = "locust-shadow"
version = "0.1.0"
description = "locust-shadow"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.88",
    "locust",
    "PyYAML",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
